auth_enabled: false
server:
  http_listen_port: 3100
  grpc_listen_port: 9096
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  wal:
    dir: /loki/wal
limits_config:
  allow_structured_metadata: true
schema_config:
  configs:
    - from: 2025-06-28
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h
      chunks:
        prefix: chunk_
        period: 24h
storage_config:
  tsdb_shipper:
    active_index_directory: /loki/tsdb-index
    cache_location: /loki/tsdb-cache
  filesystem:
    directory: /loki/chunks
compactor:
  working_directory: /loki/compactor
