services:  
  coordinator:
    image: dist-inf/coordinator-dev
    build:
      target: dev
    volumes:
      - .:/workspace
      - coordinator-dev-venv:/opt/venv
    environment:
      - PYTHONPATH=/workspace/coordinator/app
      # - UV_PROJECT_ENVIRONMENT=/opt/venv

volumes:
  coordinator-dev-venv: