# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/inference.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'proto/inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/inference.proto\x12\tinference\"6\n\x0cInferRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x12\n\ninput_data\x18\x02 \x01(\t\"s\n\rInferResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x13\n\x0boutput_data\x18\x02 \x01(\t\x12\x11\n\tworker_id\x18\x03 \x01(\t\x12\x0f\n\x07success\x18\x04 \x01(\x08\x12\x15\n\rerror_message\x18\x05 \x01(\t\"%\n\x10HeartbeatRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\"\"\n\x11HeartbeatResponse\x12\r\n\x05\x61live\x18\x01 \x01(\x08\x32\x8c\x01\n\x06Worker\x12:\n\x05Infer\x12\x17.inference.InferRequest\x1a\x18.inference.InferResponse\x12\x46\n\tHeartbeat\x12\x1b.inference.HeartbeatRequest\x1a\x1c.inference.HeartbeatResponse2N\n\x0b\x43oordinator\x12?\n\nSubmitTask\x12\x17.inference.InferRequest\x1a\x18.inference.InferResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERREQUEST']._serialized_start=36
  _globals['_INFERREQUEST']._serialized_end=90
  _globals['_INFERRESPONSE']._serialized_start=92
  _globals['_INFERRESPONSE']._serialized_end=207
  _globals['_HEARTBEATREQUEST']._serialized_start=209
  _globals['_HEARTBEATREQUEST']._serialized_end=246
  _globals['_HEARTBEATRESPONSE']._serialized_start=248
  _globals['_HEARTBEATRESPONSE']._serialized_end=282
  _globals['_WORKER']._serialized_start=285
  _globals['_WORKER']._serialized_end=425
  _globals['_COORDINATOR']._serialized_start=427
  _globals['_COORDINATOR']._serialized_end=505
# @@protoc_insertion_point(module_scope)
