# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/private.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'proto/private.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import public_pb2 as proto_dot_public__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/private.proto\x12\x0etext_embedding\x1a\x12proto/public.proto\"/\n\x0cInferRequest\x12\x0b\n\x03ids\x18\x01 \x03(\t\x12\x12\n\ninput_data\x18\x02 \x03(\t\"\x9c\x01\n\rInferResponse\x12(\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x1a.text_embedding.ReturnCode\x12\x12\n\nreturn_msg\x18\x02 \x01(\t\x12\x11\n\tworker_id\x18\x03 \x01(\t\x12\x0b\n\x03ids\x18\x04 \x03(\t\x12-\n\nembeddings\x18\x05 \x03(\x0b\x32\x19.text_embedding.Embedding\"\x12\n\x10HeartbeatRequest\"?\n\x11HeartbeatResponse\x12*\n\x06status\x18\x01 \x01(\x0e\x32\x1a.text_embedding.StatusCode*H\n\nStatusCode\x12\r\n\tSTATUS_OK\x10\x00\x12\x13\n\x0fSTATUS_DEGRADED\x10\x01\x12\x16\n\x12STATUS_UNAVAILABLE\x10\x02\x32\xa0\x01\n\x06Worker\x12\x44\n\x05Infer\x12\x1c.text_embedding.InferRequest\x1a\x1d.text_embedding.InferResponse\x12P\n\tHeartbeat\x12 .text_embedding.HeartbeatRequest\x1a!.text_embedding.HeartbeatResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.private_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUSCODE']._serialized_start=352
  _globals['_STATUSCODE']._serialized_end=424
  _globals['_INFERREQUEST']._serialized_start=59
  _globals['_INFERREQUEST']._serialized_end=106
  _globals['_INFERRESPONSE']._serialized_start=109
  _globals['_INFERRESPONSE']._serialized_end=265
  _globals['_HEARTBEATREQUEST']._serialized_start=267
  _globals['_HEARTBEATREQUEST']._serialized_end=285
  _globals['_HEARTBEATRESPONSE']._serialized_start=287
  _globals['_HEARTBEATRESPONSE']._serialized_end=350
  _globals['_WORKER']._serialized_start=427
  _globals['_WORKER']._serialized_end=587
# @@protoc_insertion_point(module_scope)
