# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/public.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'proto/public.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/public.proto\x12\x0etext_embedding\"\x1d\n\x0c\x45mbedRequest\x12\r\n\x05texts\x18\x01 \x03(\t\"\x89\x01\n\rEmbedResponse\x12(\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x1a.text_embedding.ReturnCode\x12\x12\n\nreturn_msg\x18\x02 \x01(\t\x12\x0b\n\x03ids\x18\x03 \x03(\t\x12-\n\nembeddings\x18\x04 \x03(\x0b\x32\x19.text_embedding.Embedding\"\x1b\n\tEmbedding\x12\x0e\n\x06vector\x18\x01 \x03(\x02*\x1f\n\nReturnCode\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x32U\n\rTextEmbedding\x12\x44\n\x05\x45mbed\x12\x1c.text_embedding.EmbedRequest\x1a\x1d.text_embedding.EmbedResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.public_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RETURNCODE']._serialized_start=238
  _globals['_RETURNCODE']._serialized_end=269
  _globals['_EMBEDREQUEST']._serialized_start=38
  _globals['_EMBEDREQUEST']._serialized_end=67
  _globals['_EMBEDRESPONSE']._serialized_start=70
  _globals['_EMBEDRESPONSE']._serialized_end=207
  _globals['_EMBEDDING']._serialized_start=209
  _globals['_EMBEDDING']._serialized_end=236
  _globals['_TEXTEMBEDDING']._serialized_start=271
  _globals['_TEXTEMBEDDING']._serialized_end=356
# @@protoc_insertion_point(module_scope)
