global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'coordinator'
    static_configs:
      - targets: ['coordinator:8000']
  - job_name: 'worker'
    dns_sd_configs:
      - names: ['worker']
        type: 'A'
        port: 8000