services:  
  worker:
    image: dist-inf/worker-dev
    build:
      target: dev
    volumes:
      - .:/workspace
      - worker-dev-venv:/opt/venv
    environment:
      - PYTHONPATH=/workspace/worker/app
      # - UV_PROJECT_ENVIRONMENT=/opt/venv

volumes:
  worker-dev-venv: