FROM debian:latest as dev

RUN apt -qy update && apt -qy install \
    curl \
    ca-certificates
RUN apt clean

# Download the latest installer
ADD https://astral.sh/uv/0.7.14/install.sh /uv-installer.sh

# Run the installer then remove it
RUN sh /uv-installer.sh && rm /uv-installer.sh

# Ensure the installed binary is on the `PATH`
ENV PATH="/root/.local/bin/:$PATH"

# ENV UV_LINK_MODE=copy

# WORKDIR /venv

# RUN --mount=type=cache,target=/root/.cache/uv \
#     --mount=type=bind,source=uv.lock,target=uv.lock \
#     --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
#     uv sync --locked --no-install-project

FROM dev as release


ENTRYPOINT ["sleep", "infinity"]