FROM debian:latest AS dev

RUN apt -qy update && apt -qy install \
    curl \
    ca-certificates \
    iproute2
RUN apt clean

# Download the latest installer
ADD https://astral.sh/uv/0.7.14/install.sh /uv-installer.sh

# Run the installer then remove it
RUN sh /uv-installer.sh && rm /uv-installer.sh

# Ensure the installed uv binary is on the `PATH`
ENV PATH="/root/.local/bin/:$PATH"

# Set the venv path
# ENV VIRTUAL_ENV=/opt/venv
ENV UV_PROJECT_ENVIRONMENT=/opt/venv

FROM dev AS release

ENV UV_COMPILE_BYTECODE=1

# Copy dependency files to a separate location
WORKDIR /deps
COPY uv.lock ./
COPY pyproject.toml ./

# Install dependencies from lockfile using cache for uv
# Cache requires buildkit to be enabled, which podman does not support
ENV UV_LINK_MODE=copy
RUN --mount=type=cache,target=/root/.cache/uv \
uv sync --locked --no-install-project

# Copy application code
COPY app/ /app/
WORKDIR /app

# Set entrypoint to use the venv python and run main.py
ENTRYPOINT ["/opt/venv/bin/python", "/app/main.py"]