server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: coordinator
    static_configs:
      - targets: ['localhost']
        labels:
          service: coordinator
          __path__: /logs/coordinator.log

  - job_name: worker
    static_configs:
      - targets: ['localhost']
        labels:
          service: worker
          __path__: /logs/worker*.log
    relabel_configs:
      - source_labels: [__path__]
        regex: '/logs/worker-(.+)\.log'
        target_label: worker_id
